name: Azure Static Web Apps CI/CD

permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          lfs: true
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Configure application
        uses: Azure/cli@v2
        id: configure_application
        with:
          # Specify the script here
          inlineScript: |
            echo "Configuring application..."
            az staticwebapp appsettings set -n ${{ secrets.AZURE_SWA_NAME }} --setting-names \
             DATABASE_URL=${{ secrets.CONFIG_DATABASE_URL }}
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
          azcliversion: latest
      - name: Get Deployment Token
        id: get_deployment_token
        uses: Azure/cli@v2
        with:
          inlineScript: |
            echo "Fetching deployment token..."
            token=$(az staticwebapp secrets list --name ${{ secrets.AZURE_SWA_NAME }} --query "properties.apiKey" -o tsv)
            echo "token=$token" >> $GITHUB_OUTPUT
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.get_deployment_token.outputs.token }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          output_location: 'build/static' # Built app content directory - optional
          api_location: 'build/server' # Api source code path - optional
          ###### End of Repository/Build Configurations ######
        env:
          PUBLIC_GITHUB_URL: ${{ github.server_url }}/${{ github.repository }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Get Deployment Token
        id: get_deployment_token
        uses: Azure/cli@v2
        with:
          inlineScript: |
            echo "Fetching deployment token..."
            token=$(az staticwebapp secrets list --name ${{ secrets.AZURE_SWA_NAME }} --query "properties.apiKey" -o tsv)
            echo "token=$token" >> $GITHUB_OUTPUT
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.get_deployment_token.outputs.token }}
          action: 'close'
